# Generated by Django 2.1.4 on 2018-12-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locshop', '0002_auto_20181227_0626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Loc',
        ),
    ]
