# Generated by Django 2.1.4 on 2018-12-27 06:26
from django.db import migrations
import json
from django.contrib.gis.geos import fromstr,Point
from pathlib import Path

#Import json
DATA_FILENAME = 'data_museum.json'

def load_data(apps, schema_editor):
    Loc = apps.get_model('locshop', 'Loc')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name','no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = Point(longitude,latitude, srid=4326)
                    Loc(name=name, location = location).save()
            except KeyError:
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('locshop', '0003_auto_20181227_0934'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
